#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/socket-firewall" ]]; then
  export BASH_ENV="${ZDOTDIR:-$HOME}/.zprezto/runcoms/socket-firewall"
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/socket-firewall"
fi
