#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Fix zsh

setopt MULTIOS
setopt EXTENDED_GLOB
setopt INTERACTIVECOMMENTS
unsetopt CLOBBER
unsetopt CORRECT
unalias rm 2>/dev/null
unalias scp 2>/dev/null

if [[ -z "$HOSTNAME" ]]; then
    HOSTNAME=$(hostname)
fi

# Some exports for Go

if [[ "$USER" == "cubox" ]] && [[ "$HOSTNAME" == "Sleipnir" ]]; then
    export GOPATH=~/Documents/Prog/Go
    export GOOS=darwin
    export GOARCH=amd64
    export PATH=${PATH}:/usr/local/opt/go/bin:${GOPATH}/bin
elif [[ "$USER" == "cubox" ]] && [[ "$HOSTNAME" == "Onyx" ]]; then
    export GOOS=freebsd
    export GOARCH=amd64
    export GOPATH=~/prog/Go
    export GOPATH=~/go
    export PATH=${PATH}:${GOPATH}/bin
fi

# Various exports for me

if [[ "$USER" == "cubox" ]] && [[ "$HOSTNAME" == "Sleipnir" ]]; then
    export PATH=${PATH}:$HOME/Library/Android/sdk/platform-tools
fi

if [[ "$TERM" == "screen" ]] || [[ "$TERM" == "xterm" ]]; then
    export TERM="$TERM-256color"
fi

alias tmux="tmux -2"
alias cpaste="curl -F 'content=<-' https://paste.cubox.me"
